-- 4th Wall — newer AR projects sourced from nancybakercahill.com (XR section).
-- Verbatim text + images from her portfolio detail pages. Idempotent.

insert into public.projects (slug,title,category,year,location,description,cover_image_path,status,visibility,sort_order) values
  ('substrate','Substrate','public_art',2024,'LACMA / LA Central Library / Long Beach City College','LACMA / Los Angeles Central Library / Long Beach City College

A monumental interactive AR experience, Substrate invites the viewer to consider connections between knowledge-making organizations by contributing their own descriptions of culturally significant artifacts. Borrowing imagery and examples from networks in nature, Baker Cahill depicts LACMA, the Los Angeles Public Library’s Central Library, and California’s system of community colleges as abstracted, interlocking trees with root systems and mycelial networks that produce essential nutrients for human health and well-being. The work is based on the artist’s earlier project of the same name, supported by LACMA’s Art + Technology Lab, which used futuristic civics and systems thinking to demonstrate the potential of collaborations between local civic hubs.

I am so fortunate to have received a

grant in 2022 to launch Substrate, a multi-valent experimental, collaborative systems project the first part of which is completed. The second part, an AR visualization, will follow in future months.

In the face of compounding, interconnected global crises, Substrate, an experimental art project in futuristic civics, looks for solutions in nature, focusing on biomimicry. Mycelial networks provide a robust model as networks that supply decentralized, self-sustaining, reciprocal, efficient systems of community care and resource-sharing to the interdependent carbon-based life they support. Our shared social, economic and environmental futures may depend on learning from this blueprint for “moral economies,” privileging the health and sustenance of the entire system over the needs of discrete individuals. Emerging technologies that contain the structural capacity for similar systems, including distributed ledgers of blockchains, decentralized autonomous organizations (DAOs), and the novel virtuality and interoperability of a “Web3” internet may provide new models for redistributing and protecting cultural knowledge and culturally-specific epistemologies, an early (but by no means solitary) step toward generating more equitable civic futures.

This initial community-determined exhibition, minted, encrypted and time-stamped on the blockchain, will be shareable, traceable and adaptable through the vast network of libraries in California and throughout the United States. This model is designed to be adapted and further developed for additional contexts and community needs/interests. The project is thus forming a substrate – an ever-expanding, accessible foundation of experimental exhibitions and new (and hopefully unexpected) forms of cultural engagement from which interested communities might be equitably and creatively sustained.

Click here to read the full whitepaper

by Shereen Moustafa, Mark Sosa, Casper Torres, Miguel Zavala','https://nancybakercahill.com/wp-content/uploads/2025/04/Substrate-Thumb.jpg','published','public',1)
on conflict (slug) do update set title=excluded.title,category=excluded.category,year=excluded.year,location=excluded.location,description=excluded.description,cover_image_path=excluded.cover_image_path,status=excluded.status,visibility=excluded.visibility,sort_order=excluded.sort_order;
delete from public.project_media where project_id in (select id from public.projects where slug='substrate');
insert into public.project_media (project_id,kind,url,sort_order) select id,'image','https://nancybakercahill.com/wp-content/uploads/2025/04/Substrate-LACMA.jpg',0 from public.projects where slug='substrate';
insert into public.project_media (project_id,kind,url,sort_order) select id,'image','https://nancybakercahill.com/wp-content/uploads/2024/05/Title-Frame_Substrate_00917.png',1 from public.projects where slug='substrate';
insert into public.project_media (project_id,kind,url,sort_order) select id,'image','https://nancybakercahill.com/wp-content/uploads/2024/06/P1.jpg',2 from public.projects where slug='substrate';
insert into public.project_media (project_id,kind,url,sort_order) select id,'image','https://nancybakercahill.com/wp-content/uploads/2024/06/P2.jpg',3 from public.projects where slug='substrate';
insert into public.project_media (project_id,kind,url,sort_order) select id,'image','https://nancybakercahill.com/wp-content/uploads/2024/06/P3.jpg',4 from public.projects where slug='substrate';
insert into public.project_media (project_id,kind,url,sort_order) select id,'image','https://nancybakercahill.com/wp-content/uploads/2024/06/P4.jpg',5 from public.projects where slug='substrate';
insert into public.project_media (project_id,kind,url,sort_order) select id,'image','https://nancybakercahill.com/wp-content/uploads/2024/06/P5.jpg',6 from public.projects where slug='substrate';
insert into public.project_media (project_id,kind,url,sort_order) select id,'image','https://nancybakercahill.com/wp-content/uploads/2024/06/P6.jpg',7 from public.projects where slug='substrate';
insert into public.project_media (project_id,kind,url,sort_order) select id,'image','https://nancybakercahill.com/wp-content/uploads/2024/06/P7.jpg',8 from public.projects where slug='substrate';
insert into public.project_media (project_id,kind,url,sort_order) select id,'image','https://nancybakercahill.com/wp-content/uploads/2024/06/P8.jpg',9 from public.projects where slug='substrate';
insert into public.project_media (project_id,kind,url,sort_order) select id,'image','https://nancybakercahill.com/wp-content/uploads/2024/06/P9.jpg',10 from public.projects where slug='substrate';
insert into public.project_media (project_id,kind,url,sort_order) select id,'image','https://nancybakercahill.com/wp-content/uploads/2024/06/P10.jpg',11 from public.projects where slug='substrate';

insert into public.projects (slug,title,category,year,location,description,cover_image_path,status,visibility,sort_order) values
  ('cento','CENTO','public_art',2023,null,'is a global, participatory art project in immersive video and augmented reality focused on a bioengineered future creature that is presented as an experimental, living test for evolutionary fitness in the face of the sixth extinction. We are rapidly entering a moment where synthetic biology is progressing from hypothetical to incarnate– with gene editing, GMOs, biomimetics, and bioprospecting deployed in a variety of contexts. Many of these experiments serve controversial militaristic, capitalistic, or socially/environmentally controversial purposes. Decoupled from such extractive interests, the question Cento asks is, would a creature imagined as a collage of human, cephalopod, microbiome, avian, mycelial, marine, and machine attributes fulfill or even exceed basic evolutionary requirements? What traits will ensure survival and could we find hope in a blended future creature? What would a bio-ethically produced transspeciated self look like and how might it move through space? How might we reconsider what Rosi Braidotti calls “the embrainment of the body” when a body contains multiple types of embodied knowledge? Could species egalitarianism exist in the body politic of a new hybrid creature?

The focus of the interactive AR component presented in the immersive video is the collective responsibility required in the task of survival. People all over the globe can participate in

''s co-creation and survival by adding feathers through the 4th Wall app to the creature, each one endowed with a different property to ensure evolutionary fitness. When viewers add their respective feathers to the creature, Cento will change and grow stronger in real time on site at the Whitney, growing evolutionarily more fit with the engagement of an ever expanding collective of participants. My hope is that this morphing over time will underscore the necessity of collaborative action, and materialize species interdependence and biological inextricability. Also featured is

''s imagined future habitat—a blended nest, lair, network captured in the immersive video below.

Production by Nancy Baker Cahill

Three stages of CENTO''s Evolution (most recent capture by Jessica Sung, January 2024).','https://nancybakercahill.com/wp-content/uploads/2023/09/CentoThumb.png','published','public',2)
on conflict (slug) do update set title=excluded.title,category=excluded.category,year=excluded.year,location=excluded.location,description=excluded.description,cover_image_path=excluded.cover_image_path,status=excluded.status,visibility=excluded.visibility,sort_order=excluded.sort_order;
delete from public.project_media where project_id in (select id from public.projects where slug='cento');
insert into public.project_media (project_id,kind,url,sort_order) select id,'image','https://nancybakercahill.com/wp-content/uploads/2023/09/1920x1080-screenshot-40-1.png',0 from public.projects where slug='cento';
insert into public.project_media (project_id,kind,url,sort_order) select id,'image','https://nancybakercahill.com/wp-content/uploads/2024/04/CENTO-Thumb-2.jpg',1 from public.projects where slug='cento';
insert into public.project_media (project_id,kind,url,sort_order) select id,'image','https://nancybakercahill.com/wp-content/uploads/2023/09/cento_habitat_whitney-.png',2 from public.projects where slug='cento';
insert into public.project_media (project_id,kind,url,sort_order) select id,'image','https://nancybakercahill.com/wp-content/uploads/2023/11/cento1.jpg',3 from public.projects where slug='cento';
insert into public.project_media (project_id,kind,url,sort_order) select id,'image','https://nancybakercahill.com/wp-content/uploads/2023/11/cento2.jpg',4 from public.projects where slug='cento';
insert into public.project_media (project_id,kind,url,sort_order) select id,'image','https://nancybakercahill.com/wp-content/uploads/2024/04/CENTO_horizontal_300dpi-scaled.jpg',5 from public.projects where slug='cento';

insert into public.projects (slug,title,category,year,location,description,cover_image_path,status,visibility,sort_order) values
  ('lifelines','Lifelines','public_art',2023,null,'is an animated, monumental, augmented reality installation of ecological imagination.

Geolocated in the Prime Desert Woodland Preserve (PDWP), a protected, historic desert in California''s Antelope Valley,

, appears as three collossal Joshua trees surrounded by a ghostly murmuration of birds. Rich with wildlife and home to many species of insects, reptiles, mammals, and birds, this fragile ecosystem remains imperiled. The ongoing precarity offers and opportunity to reframe our interdependent relationship with this natural ecosystem and modes of planetary knowledge erased by the progress of modernity. The Antelope Valley, like so many other regions is also a home to narratives of this land for centuries. Human appetites for exponential growth and advancement have caused enormous harm: ecological, historical, and cultural.

underscores the majesty of Joshua trees in the form of towering, breathing trees that rhythmically expand and contract. They have been rendered digitally with glowing interiors, glimpsed with each exhale, to imply a mythic grandeur. By scaling the trees to colossal proportions, the work challenges human exceptionalism. AR as a medium allows viewers to re-embed the human experience in nature without harming local flora and fauna, and to embrace new modes of perceiving. Unlike other forms of land art, AR is distinct in its ability to be both present and absent, to reveal what otherwise goes unseen, unheard, and unimagined.

An elegiac melody, which weaves together five native bird songs, ambient desert sounds, and breathing, plays throughout the experience - at once celebratory, melancholy, and resilient. Bird songs are essential to

, not just because of the plurality of songs heard today, but because of the traditional "Bird Songs" of the region''s First Peoples, social and funeral songs that tell migration stories, shared memories, and histories. To move through the PDWP is to encounter its enduring planetary intelligence, above and below ground. It offers a rare glimpse into how a protected desert ecosystem might thrive when treated with care and respect.

invites new considerations for its troubled past, imperiled present, and modes of inherited knowledge, which present the possibility of regenerative futures here and beyond.

Soundscape by Anna Luisa Petrisko

Production by Nancy Baker Cahill and

Special thanks to Caleb Craig and Shaking Earth Digital.','https://nancybakercahill.com/wp-content/uploads/2023/09/MicrosoftTeams-image.jpg','published','public',3)
on conflict (slug) do update set title=excluded.title,category=excluded.category,year=excluded.year,location=excluded.location,description=excluded.description,cover_image_path=excluded.cover_image_path,status=excluded.status,visibility=excluded.visibility,sort_order=excluded.sort_order;
delete from public.project_media where project_id in (select id from public.projects where slug='lifelines');
insert into public.project_media (project_id,kind,url,sort_order) select id,'image','https://nancybakercahill.com/wp-content/uploads/2024/04/4th-Wall-2023-10-03_08-58-37.png',0 from public.projects where slug='lifelines';
insert into public.project_media (project_id,kind,url,sort_order) select id,'image','https://nancybakercahill.com/wp-content/uploads/2024/04/Nigh-Lifelines-BG.jpg',1 from public.projects where slug='lifelines';

insert into public.projects (slug,title,category,year,location,description,cover_image_path,status,visibility,sort_order) values
  ('state-property','State Property','public_art',2022,null,'STATE PROPERTY, digital sculpture, 2022

State Property, a digital neon sculpture of an exploded uterus, refers to court-ordered, state-sanctioned intervention on bodies, where wombs become disembodied sites of legal and criminal action. Forced birth is violent. Cruel externalities, known and yet to come, are represented in the organ’s fracturing. State Property underscores the corruption of what should be an individual''s autonomous right to decide the circumstances under which reproduction occurs. Neon, often a language of cheap advertising, reflects the false promises of maternal support after birth.

The fundamentalist salvo overturning Roe represents not just a constitutional crisis of personhood and an abject abuse of power, but one of precedent; public statements indicate that marriage equality and contraceptive rights are also now in the crosshairs. In this historic moment, artistic interventions will play a critical role in provoking meaningful public discourse and action. EPOCH offers an accessible and interactive opportunity to engage the public through powerful artwork, shared resources, and funding for reproductive justice.

UNPROTECTED is modeled after the Supreme Court of the United States building and is organized in response to the US Supreme Court decision to overturn Roe v. Wade, leaving millions of Americans stripped of bodily autonomy. The overturning represents not just a constitutional crisis of personhood and an abject abuse of power, but one with a growing range of cruel externalities beyond forced birth; including preventable infections, lost access to crucial autoimmune medications, and death. The state-sanctioned criminalization and surveillance of those seeking and providing reproductive care has a radial impact on the health care providers, family and friends who are involved in supporting pregnant individuals. Increased morbidities, poverty and incarceration will be inevitable and widespread outcomes. It isn’t enough to go back to the precarious protections afforded by Roe, in which many, especially impoverished people of color, were already forced into dangerous decisions between their livelihood and safe healthcare. Many lawmakers have already vowed even more sweeping national criminalization of pregnancy and contraception (along with increased targeting of all bodies that are not cisgender, heterosexual and male) as soon as Republicans once again control both houses of Congress. Voting blue is not enough. Today, our voices must be heard in every possible forum, state and federal: Reproductive justice and equitable abortion access must be enshrined in the Constitution, immediately. In this historic moment, artistic interventions will play a critical role in provoking meaningful public discourse and action. EPOCH offers an accessible and interactive opportunity to engage the public through powerful artwork, shared resources, and funding for reproductive justice.

On August 13th, the entirety of the UNPROTECTED exhibition will be released as a singular NFT containing a compilation of artworks by participating artists. A portion of the proceeds will go to support reproductive justice organizations.

UNPROTECTED, graphite drawing, 2017

On September 28, 2018, during Dr. Ford’s testimony against now Justice Kavanaugh, I geolocated a drawing of mine in augmented reality (AR), titled Unprotected, in front of the United States Supreme Court. The drawing hailed from my Surds series, which explored trauma responses in the body and embodied knowledge. The Surds series was inspired by a powerful book of feminist philosophy by Susan J. Brison called Aftermath, which addressed the author’s metabolization of her own sexual assault. I appended the word “Unprotected” to my AR drawing for two reasons. The first was obvious; during Dr. Ford’s testimony, as during Anita Hill’s decades earlier, millions of Americans were reminded of the dearth of judicial protections for victims of sexual assault and of the cultural systems that continue to erase, mock and intimidate those who dare to speak up. The second was a reminder that the Equal Rights Amendment (ERA) has never been ratified; more than half of American citizens remain unequally protected under the law. At the time, it felt astonishing in 2018. As of June 24, 2022, it appears it may never be ratified.','https://nancybakercahill.com/wp-content/uploads/2022/08/StatePropertyFB.jpg','published','public',4)
on conflict (slug) do update set title=excluded.title,category=excluded.category,year=excluded.year,location=excluded.location,description=excluded.description,cover_image_path=excluded.cover_image_path,status=excluded.status,visibility=excluded.visibility,sort_order=excluded.sort_order;
delete from public.project_media where project_id in (select id from public.projects where slug='state-property');
insert into public.project_media (project_id,kind,url,sort_order) select id,'image','https://nancybakercahill.com/wp-content/uploads/2022/08/StatePropertyTwit.jpg',0 from public.projects where slug='state-property';
insert into public.project_media (project_id,kind,url,sort_order) select id,'image','https://nancybakercahill.com/wp-content/uploads/2022/08/Unprotected_6_StateProperty.png',1 from public.projects where slug='state-property';
insert into public.project_media (project_id,kind,url,sort_order) select id,'image','https://nancybakercahill.com/wp-content/uploads/2022/08/Unprotected_5_StateProperty.png',2 from public.projects where slug='state-property';
insert into public.project_media (project_id,kind,url,sort_order) select id,'image','https://nancybakercahill.com/wp-content/uploads/2022/08/Unprotected_2.png',3 from public.projects where slug='state-property';
insert into public.project_media (project_id,kind,url,sort_order) select id,'image','https://nancybakercahill.com/wp-content/uploads/2022/08/Unprotected_4.png',4 from public.projects where slug='state-property';

insert into public.projects (slug,title,category,year,location,description,cover_image_path,status,visibility,sort_order) values
  ('slipstream-times-square','Slipstream Times Square','public_art',2022,'Times Square, New York','Nancy Baker Cahill’s Slipstream Times Square transfigures the bewildering, dizzying energy of Times Square through a pulsing, heaving, abstract artwork on 90 screens. This artwork springs from Baker Cahill’s multi-media Slipstream series, which trafficks in slipstream fiction’s familiar strange or strange familiar via “epistemological and ontological questionings about reality,” and provides the conceptual framework for the video. Slipstream Times Square, like other videos in the series, dwells in the murky territories of consciousness, but does so here multiplied, at scale, for a collective public audience. This artwork gestures towards the organic, as a simulated fiction of botanical and biomorphic forms. Spread across millions of LED nodes, It offers a familiar referent with no natural analogue.

Hybridity is the beating heart of the artwork. Slipstream Times Square attempts to collapse traditional moving images and screens with a living, breathing artwork that threatens to spill out and into open shared space. Graphite drawings, torn into sculptures which form the shifting landscape in the video, glisten as they breathe, expand, and contract. Occupying space normally reserved for capitalistic exhortations, the video slyly reveals the non-commercial analog technology of drawing, blurring its origins with dazzling pixels and bringing it to life for viewers. Slipstream Times Square aims to transform this iconic space by inviting conversations about what is real, what is alive, and what we see and feel when digital/analog boundaries are blurred.','https://nancybakercahill.com/wp-content/uploads/2022/07/TimesSquareSlipstreamFB.jpg','published','public',5)
on conflict (slug) do update set title=excluded.title,category=excluded.category,year=excluded.year,location=excluded.location,description=excluded.description,cover_image_path=excluded.cover_image_path,status=excluded.status,visibility=excluded.visibility,sort_order=excluded.sort_order;
delete from public.project_media where project_id in (select id from public.projects where slug='slipstream-times-square');
insert into public.project_media (project_id,kind,url,sort_order) select id,'image','https://nancybakercahill.com/wp-content/uploads/2022/07/TimesSquareSlipstreamtwit.jpg',0 from public.projects where slug='slipstream-times-square';
insert into public.project_media (project_id,kind,url,sort_order) select id,'image','https://nancybakercahill.com/wp-content/uploads/2022/07/SlipstreamTimesSquareHorizontal.jpg',1 from public.projects where slug='slipstream-times-square';
insert into public.project_media (project_id,kind,url,sort_order) select id,'image','https://nancybakercahill.com/wp-content/uploads/2022/07/NBC_TimesSquare0.png',2 from public.projects where slug='slipstream-times-square';
insert into public.project_media (project_id,kind,url,sort_order) select id,'image','https://nancybakercahill.com/wp-content/uploads/2022/07/countdown0000-1.png',3 from public.projects where slug='slipstream-times-square';
